### ISSUE TITLE
Change the Padding in the Buttons

### ISSUE THREAD

**Issue by Pilag6** [TongueBit/ItalianCitizenshipReview#59]
Hey Tony, how are you? 

You project is growing so fast. Congrats!!!

We have to start to work in the UI. Lets find some time. 

I am going to start with something small but that can change the UI a bit.

I found that you can have more space in the buttons to looks more clean. 

Since you are using Bootstrap you can add to them `px2 py3` 

![image](https://github.com/TongueBit/ItalianCitizenshipReview/assets/79191808/bb4ea05d-d226-45d4-b118-ae7bcdb2961c)

![image](https://github.com/TongueBit/ItalianCitizenshipReview/assets/79191808/aef05d75-bfc2-4d49-8ee1-19dc2f55a921)

**Comment by TongueBit** [comment]
Thanks Pila! Just updated it! 

![Screenshot 2023-08-23 at 5 00 09 PM](https://github.com/TongueBit/ItalianCitizenshipReview/assets/58486280/b7f4e58d-3755-4d12-a1b0-c7228a243905)
